num1 = int(input("Num 1 : "))
num2 = int(input("Num 2 : "))
a = num1 + num2
b = num1 - num2
c = num1 * num2
d = num1 / num2
print(num1,"+",num2,"=",a)
print(num1,"-",num2,"=",b)
print(num1,"*",num2,"=",c)
print(num1,"/",num2,"=",d)
